// Generated by gencpp from file qtnp/InitialCoordinates.msg
// DO NOT EDIT!


#ifndef QTNP_MESSAGE_INITIALCOORDINATES_H
#define QTNP_MESSAGE_INITIALCOORDINATES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace qtnp
{
template <class ContainerAllocator>
struct InitialCoordinates_
{
  typedef InitialCoordinates_<ContainerAllocator> Type;

  InitialCoordinates_()
    : uav_id(0)
    , longitude(0.0)
    , latitude(0.0)  {
    }
  InitialCoordinates_(const ContainerAllocator& _alloc)
    : uav_id(0)
    , longitude(0.0)
    , latitude(0.0)  {
  (void)_alloc;
    }



   typedef int8_t _uav_id_type;
  _uav_id_type uav_id;

   typedef double _longitude_type;
  _longitude_type longitude;

   typedef double _latitude_type;
  _latitude_type latitude;




  typedef boost::shared_ptr< ::qtnp::InitialCoordinates_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::qtnp::InitialCoordinates_<ContainerAllocator> const> ConstPtr;

}; // struct InitialCoordinates_

typedef ::qtnp::InitialCoordinates_<std::allocator<void> > InitialCoordinates;

typedef boost::shared_ptr< ::qtnp::InitialCoordinates > InitialCoordinatesPtr;
typedef boost::shared_ptr< ::qtnp::InitialCoordinates const> InitialCoordinatesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::qtnp::InitialCoordinates_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::qtnp::InitialCoordinates_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace qtnp

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'qtnp': ['/home/fotis/Dev/Workspaces/ROS/qTnP/src/qtnp/msg'], 'visualization_msgs': ['/opt/ros/indigo/share/visualization_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::qtnp::InitialCoordinates_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qtnp::InitialCoordinates_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qtnp::InitialCoordinates_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qtnp::InitialCoordinates_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qtnp::InitialCoordinates_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qtnp::InitialCoordinates_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::qtnp::InitialCoordinates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d5d8ffa4c93324dbf2bbc015565b6f30";
  }

  static const char* value(const ::qtnp::InitialCoordinates_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd5d8ffa4c93324dbULL;
  static const uint64_t static_value2 = 0xf2bbc015565b6f30ULL;
};

template<class ContainerAllocator>
struct DataType< ::qtnp::InitialCoordinates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "qtnp/InitialCoordinates";
  }

  static const char* value(const ::qtnp::InitialCoordinates_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::qtnp::InitialCoordinates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 uav_id\n\
float64 longitude\n\
float64 latitude\n\
";
  }

  static const char* value(const ::qtnp::InitialCoordinates_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::qtnp::InitialCoordinates_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.uav_id);
      stream.next(m.longitude);
      stream.next(m.latitude);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InitialCoordinates_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::qtnp::InitialCoordinates_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::qtnp::InitialCoordinates_<ContainerAllocator>& v)
  {
    s << indent << "uav_id: ";
    Printer<int8_t>::stream(s, indent + "  ", v.uav_id);
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QTNP_MESSAGE_INITIALCOORDINATES_H
